# Generated by Django 5.1.3 on 2024-11-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdesarrolladores', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('D', 'Desarrollador'), ('L', 'Lider')], default='B', max_length=1),
        ),
    ]
