# Generated by Django 5.1.3 on 2024-11-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectdesarrolladores', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_inicio',
        ),
    ]
