# Generated by Django 5.1.3 on 2024-11-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdesarrolladores', '0005_remove_proyecto_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('D', 'Desarrollador'), ('L', 'Líder')], default='D', max_length=1),
        ),
    ]
