# Generated by Django 5.1.3 on 2024-11-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdesarrolladores', '0007_alter_tarea_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
